### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ReinforceZwei** [ReinforceZwei/personal-subscription-record#2]
- [x] Subscription record page
- [x] Translate to Chinese
- [x] Add more instruction for first-time user
- [x] Add logout button
- [x] Add switch for light/dark/follow system mode
- [x] Add weight ordering for type and payment
- [x] ~~Allow icon to be used on type and payment~~ emoji is enough
- [x] Allow set type/payment to enable or disable (replacement for delete)
- [ ] Allow disable name suggestion for a type
- [x] Add budget setting for type/global
- [ ] Add message for new user have type but no payment
- [x] Allow type to have default payment
- [x] Show spending sum/details by type
- [x] Allow edit record
- [ ] Add calendar view for records
- [x] Add charts
- [x] Migrate project to typescript (https://github.com/vitejs/vite/discussions/6799#discussioncomment-5393727)
